### ISSUE TITLE
python packages problem

### ISSUE THREAD

**Issue by yoni333** [liaveliyahu/DragGAN_with_Adaptive_GAN#2]
i use the project with dockerfile , i got error when i run it

`Traceback (most recent call last):
  File "/workspace/src/visualizer_drag_gradio.py", line 205, in <module>
    global_state = init_images(global_state)
  File "/workspace/src/visualizer_drag_gradio.py", line 96, in init_images
    add_watermark_np(np.array(init_image)))
  File "/workspace/src/viz/renderer.py", line 56, in add_watermark_np
    text_width, text_height = font.getsize(watermark_text)
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'`

**Comment by yoni333** [comment]
it is a problem with a function that add water mark to the picture.it use font in a way the new packages came from pip install dont know to use - 
solution comment the call to this function in line rendere.py  line 121
`#             res.image = add_watermark_np(res.image, 'AI Generated')
`
in the function def renderer.
also comment the txt creation in  the function "add_watermark_np" like this and return the original picture
```
def add_watermark_np(input_image_array, watermark_text="AI Generated"):
    image = Image.fromarray(np.uint8(input_image_array)).convert("RGBA")

    # Initialize text image
   # txt = Image.new('RGBA', image.size, (255, 255, 255, 0))
   # font = ImageFont.truetype('arial.ttf', round(25/512*image.size[0]))
   # d = ImageDraw.Draw(txt)

   # text_width, text_height = font.getsize(watermark_text)
   # text_position = (image.size[0] - text_width - 10, image.size[1] - text_height - 10)
   # text_color = (255, 255, 255, 128)  # white color with the alpha channel set to semi-transparent

   # # Draw the text onto the text canvas
   # d.text(text_position, watermark_text, font=font, fill=text_color)

    # Combine the image with the watermark
    # watermarked = Image.alpha_composite(image, txt)
    watermarked_array = np.array(image)
    return watermarked_array
```
